# Generated by Django 5.1.6 on 2025-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_class', models.CharField(max_length=200)),
                ('mark_subject_1', models.IntegerField()),
                ('mark_subject_2', models.IntegerField()),
                ('mark_subject_3', models.IntegerField()),
                ('total_mark', models.IntegerField(editable=False)),
            ],
        ),
    ]
